### ISSUE TITLE
Discussion your roadmap and evolution

### ISSUE THREAD

**Issue by Larandar** [whopavan/alfred-todoist#1]
Hello, this is not an issue, but I would like to discuss it with you.

First, using the v2 API is great; the other todoist workflows use the v1 and therefore are not able to keep up with new features :)
 
What are the evolutions you are open to and your ultimate roadmap:

- Move todoists interaction to be a library in a different language (Python, JS/TS, Rust, or Go, for example) and have Alfred only interact with top-level abstractions
  - Would allow contributors to maintain the codebase in a more streamlined way (tests, ci/cd, ...)
  - Some features would be trivial in non-ZSH (ex: https://docs.rs/humantime/latest/humantime/)
  - Could even do OAuth2 negotiation with todoist instead of manually creating a token? 
- Support for projects
- Add more features: `done` and `todos` (list next task) being the most useful IMO

**Comment by whopavan** [comment]
Hey, first of all thanks for asking.

The reason I created this even though there is a [Alfred workflow for todoist](https://github.com/moranje/alfred-workflow-todoist) _**is because, it required additional installation (like npm), I DO NOT use npm in my day to day work so installing it only to get the workflow working didn't make sense to me**_.

Now coming to your point



> Move todoists interaction to be a library in a different language (Python, JS/TS, Rust, or Go, for example) and have Alfred only interact with top-level abstractions
> * Would allow contributors to maintain the codebase in a more streamlined way (tests, ci/cd, ...)
> * Some features would be trivial in non-ZSH (ex: https://docs.rs/humantime/latest/humantime/)
> * Could even do OAuth2 negotiation with todoist instead of manually creating a token?

When I was creating the workflow I did think of this for the future by also maintaining **_"no additional installations"_** for the users. I would say this is a P1, and I might work on this around Christmas time.



> * Support for projects
> * Add more features: `done` and `todos` (list next task) being the most useful IMO

Agree, these are some basic functionality a user would expect. I'll try to add them one by one in my free time.
Do contribute if you wish to 🙂

**Comment by Larandar** [comment]
If you are open to it, I would be delighted to start a companion rust library / cli.

The workflow could ship the binary (with all the problem macOS give to downloaded binaries) or use `brew install todoist-cli` for example if we manage to get it published on homebrew (or `cargo install`)

Else there are a few higher level programming language that are expected to be installed on macOS: python, ruby or perl for example.

**Comment by whopavan** [comment]
Hey, sure, go ahead. I would say use python 3.x, you'll write less code plus pre-installed on all MacOS. One less thing for user to install.
